source 'https://github.com/CocoaPods/Specs.git'  # 官方库
source 'https://github.com/TuyaInc/TYPublicSpecs.git'

platform :ios, '8.0'

target 'TYTabBarController_Example' do
  pod 'TYTabBarController', :path => '../'

  target 'TYTabBarController_Tests' do
    inherit! :search_paths

    
  end
end
